server:
  port: 8003

spring:
  application:
    name: member-storage-system
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss

logging:
  level:
    com.member.storage: DEBUG
    org.springframework.web: INFO
